#*****************************************************************************
# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

#*****************************************************************************

# usage:
# scons VARIANT=debug TARG=linux WS=off 
#    optional additional parameters:
#        AJ_TCL_ROOT=path/to/ajtcl
#        <name of target to build>
# sample usage:
# scons VARIANT=debug TARG=linux WS=off AJ_TCL_ROOT=../../../../../core/ajtcl

ajtcl_root_default = '../../../../../core/ajtcl'

env = SConscript(ajtcl_root_default + '/SConscript')

# we create a cloned ajtcl environment, so we don't taint ajtcl build with our defines and flags
cps_env = env.Clone()
Export('cps_env')
cps_env.SConscript('SConscript')