# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('appsCommon_env')

srcs = ['PropertyStore.c']
if 'common_samples_srcs' in appsCommon_env:
    srcs.extend(appsCommon_env['common_samples_srcs'])

objs = appsCommon_env.Object(srcs)

Return('objs')

