#*****************************************************************************
# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

#*****************************************************************************

import os

Import('time_env')

time_env.Append(CPPDEFINES = ['TIME_SERVICE_COMMON'])

srcs = [Glob('*.c')]

time_env.Append(CPPPATH = [
                             Dir('../../../inc'),
                            ])

Export('time_env')

objs = time_env.Object(srcs)

Return('objs')

