# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


import os.path
ajtcl_root_default = '../../../../core/ajtcl'
ajtcl_root = ARGUMENTS.get('AJ_TCL_ROOT', ajtcl_root_default)
if not os.path.isfile(ajtcl_root + '/SConscript'):
    print "SConscript in 'AJ_TCL_ROOT=" + ajtcl_root + "' not found; aborting.\n"
    exit(1)
env = SConscript(ajtcl_root + '/SConscript')
env['CPPDEFINES'].remove('AJ_NUM_REPLY_CONTEXTS=8')
env.Append(CPPDEFINES = ['AJ_NUM_REPLY_CONTEXTS=2', 'AJ_MAX_OBJECT_LISTS=9'])
env.SConscript('SConscript', variant_dir = 'obj', duplicate = 0)